package Coding;

import Tables.All_Books;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.JTextField;
import javax.swing.text.NumberFormatter;
import org.apache.commons.compress.utils.IOUtils;

/**
 *
 * @author Hadi
 */
public class Add_Book extends javax.swing.JFrame {

    Image image = null;
    String ImagePath = null;

    File file = new File("Icon.png");
    String absolutePath = file.getAbsolutePath().replace("Icon.png", "/src/Images/Icon.png");
    ImageIcon FrameIcon = new ImageIcon(absolutePath);
    
   JFormattedTextField textField;
   public String Online = "NO";
    
    public Add_Book() {
        initComponents();
        this.textField = ((DefaultEditor) jTextNumbers.getEditor()).getTextField();
        this.setIconImage(FrameIcon.getImage());
        JFormattedTextField txt = ((JSpinner.NumberEditor) jTextNumbers.getEditor()).getTextField();
        ((NumberFormatter) txt.getFormatter()).setAllowsInvalid(false);
        textField.setHorizontalAlignment(JTextField.LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextBookId = new javax.swing.JTextField();
        jTextBookName = new javax.swing.JTextField();
        jTextBookPublisher = new javax.swing.JTextField();
        jTextPrice = new javax.swing.JTextField();
        jTextLocation = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxEdition = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonAddBook = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelPicture = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jTextNumbers = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(new java.awt.Color(0, 0, 12));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insert Book");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jTextBookId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextBookId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextBookId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextBookIdKeyTyped(evt);
            }
        });

        jTextBookName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextBookName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextBookName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextBookNameKeyTyped(evt);
            }
        });

        jTextBookPublisher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextBookPublisher.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextBookPublisher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextBookPublisherKeyTyped(evt);
            }
        });

        jTextPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPrice.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPriceKeyTyped(evt);
            }
        });

        jTextLocation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextLocation.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextLocation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextLocationKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Book Id :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Publisher :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Available :");

        jComboBoxEdition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxEdition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First Edition", "Second Edition", "Third Edition", "Fourth Edition", "Fifth Edition", "Sixth Edition", "Seventh Edition" }));
        jComboBoxEdition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBoxEditionKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Price :");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Location :");

        jPanel3.setBackground(new java.awt.Color(0, 0, 12));

        jButtonAddBook.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddBook.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonAddBook.setText("Add Book");
        jButtonAddBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddBookMouseExited(evt);
            }
        });
        jButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBookActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setText("Close");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setText("See Books List");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButtonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("Picture");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextNumbers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextNumbers.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jTextNumbers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextNumbers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNumbersKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextBookName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextBookId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextBookPublisher, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextPrice, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextLocation)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jComboBoxEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jComboBoxEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBookActionPerformed

    if (Online.equals("YES")) {
            
            
            if(AlreadyExist_Online(jTextBookId.getText())) {
            }
            else if(jTextBookName.getText().equals("")
               || jTextBookPublisher.getText().equals("")
               || jTextPrice.getText().equals("")
//               || jTextNumbers.getValue().equals("")
               || jTextLocation.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Some Fields are empty");
            }
            else {
                
            try {
            conn con = new conn("YES");
            
            String sql = "insert into Book(book_id, bookName, publisher, price,"
                + " Numbers, location, edition, picture) values(?, ?, ?, ?, ?, ?, ?, ?)";               
            
            String sql_No_Picture = "insert into Book (book_id, bookName, publisher, price,"
                + " Numbers, location, edition) values(?, ?, ?, ?, ?, ?, ?)";
            
                if(ImagePath == null) {
                    PreparedStatement st = con.c.prepareStatement(sql_No_Picture);
                    st.setString(1, jTextBookId.getText());
                    st.setString(2, jTextBookName.getText());
                    st.setString(3, jTextBookPublisher.getText());
                    st.setString(4, jTextPrice.getText());
                    st.setString(5, jTextNumbers.getValue().toString());
                    st.setString(6, jTextLocation.getText());
                    st.setString(7, (String) jComboBoxEdition.getSelectedItem());                
                    int rs = st.executeUpdate();
                    
                
		if (rs > 0){
                    JOptionPane.showMessageDialog(null, "Book Added Succesfully without Picture");
                    ResetAllOnline();
                    jTextBookId.grabFocus();
                }
                else {
                     JOptionPane.showMessageDialog(null, "Error");
                     ResetAllOnline();
                     st.close();
                     con.c.close();
                    }
                }
                
                else
                {
                InputStream in = new FileInputStream(ImagePath);
                byte[] bytes = IOUtils.toByteArray(in);
                
		PreparedStatement st = con.c.prepareStatement(sql);
		st.setString(1, jTextBookId.getText());
		st.setString(2, jTextBookName.getText());
		st.setString(3, jTextBookPublisher.getText());
		st.setString(4, jTextPrice.getText());
		st.setString(5, jTextNumbers.getValue().toString());
		st.setString(6, jTextLocation.getText());
		st.setString(7, (String) jComboBoxEdition.getSelectedItem());
                st.setBytes(8, bytes);
		int rs = st.executeUpdate();
               
		if (rs > 0){
                    JOptionPane.showMessageDialog(null, "Succesfully Added with Picture");
                    ResetAllOnline();
                    jTextBookId.grabFocus();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error");
                    ResetAllOnline();
                    st.close();
                    con.c.close();
                    }
                }
            }
            catch(SQLException | HeadlessException | IOException e){
                JOptionPane.showMessageDialog(this, "Database Error"+e.getMessage());
            }        
        }            
        }
        
        
        
        
    else {
        
       if(AlreadyExist(jTextBookId.getText())) {
       }
       else if(jTextBookName.getText().equals("")
               || jTextBookPublisher.getText().equals("")
               || jTextPrice.getText().equals("")
//               || jTextNumbers.getValue().equals("")
               || jTextLocation.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Some Fields are empty");
       }
       else {
        try {
            conn con = new conn();
            
            String sql = "insert into Book(book_id, bookName, publisher, price,"
                + " Numbers, location, edition, picture) values(?, ?, ?, ?, ?, ?, ?, ?)";               
            
            String sql_No_Picture = "insert into Book (book_id, bookName, publisher, price,"
                + " Numbers, location, edition) values(?, ?, ?, ?, ?, ?, ?)";
            
                if(ImagePath == null) {
                    PreparedStatement st = con.c.prepareStatement(sql_No_Picture);
                    st.setString(1, jTextBookId.getText());
                    st.setString(2, jTextBookName.getText());
                    st.setString(3, jTextBookPublisher.getText());
                    st.setString(4, jTextPrice.getText());
                    st.setString(5, jTextNumbers.getValue().toString());
                    st.setString(6, jTextLocation.getText());
                    st.setString(7, (String) jComboBoxEdition.getSelectedItem());
                
                    int rs = st.executeUpdate();
                System.out.println();
		if (rs > 0){
                    JOptionPane.showMessageDialog(null, "Book succesfully Added without picture");
                    ResetAll();
                    jTextBookId.grabFocus();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error");
                    ResetAll();
                    st.close();
                    con.c.close();
                    }
                }
                
                else
                {
                InputStream in = new FileInputStream(ImagePath);
                byte[] bytes = IOUtils.toByteArray(in);
                
		PreparedStatement st = con.c.prepareStatement(sql);
		st.setString(1, jTextBookId.getText());
		st.setString(2, jTextBookName.getText());
		st.setString(3, jTextBookPublisher.getText());
		st.setString(4, jTextPrice.getText());
		st.setString(5, jTextNumbers.getValue().toString());
		st.setString(6, jTextLocation.getText());
		st.setString(7, (String) jComboBoxEdition.getSelectedItem());
                st.setBytes(8, bytes);

		int rs = st.executeUpdate();
                System.out.println();
		if (rs > 0){
                    JOptionPane.showMessageDialog(null, "Succesfully Added");
                    ResetAll();
                    jTextBookId.grabFocus();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error");
                    ResetAll();
                    st.close();
                    con.c.close();
                    }
                }
            }
            catch(SQLException | HeadlessException | IOException e){
                JOptionPane.showMessageDialog(this, "Database Error"+e.getMessage());
            }
        
        }
        }
    }//GEN-LAST:event_jButtonAddBookActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Online.equals("YES"))
        ResetAllOnline();
        else
            ResetAll();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        java.io.File f = showFileDialog(true);
        if(f == null) {
        } else
            
        try {   
        image = ImageIO.read(f);
        Image a = image.getScaledInstance(200, 250, Image.SCALE_DEFAULT);
        jLabelPicture.setIcon(new ImageIcon(a));
        this.validate();
        } catch(Exception ex) {JOptionPane.showMessageDialog(this, "Error!");}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextBookIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBookIdKeyTyped
         char num = evt.getKeyChar();
        if(num == KeyEvent.VK_ENTER)
        jTextBookId.transferFocus();
    }//GEN-LAST:event_jTextBookIdKeyTyped

    private void jTextBookNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBookNameKeyTyped
        char num = evt.getKeyChar();
        if(num == KeyEvent.VK_ENTER)
        jTextBookName.transferFocus();
    }//GEN-LAST:event_jTextBookNameKeyTyped

    private void jTextBookPublisherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBookPublisherKeyTyped
        char num = evt.getKeyChar();
        if(num == KeyEvent.VK_ENTER)
        jTextBookPublisher.transferFocus();
    }//GEN-LAST:event_jTextBookPublisherKeyTyped

    private void jTextPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPriceKeyTyped
        char num = evt.getKeyChar();
        if(num == KeyEvent.VK_ENTER)
        jTextPrice.transferFocus();
         
        else if(!(Character.isDigit(num)
                ||(num == KeyEvent.VK_BACK_SPACE)
                ||(num == KeyEvent.VK_DELETE)))
            evt.consume();
        
    }//GEN-LAST:event_jTextPriceKeyTyped

    private void jTextLocationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextLocationKeyTyped
        char num = evt.getKeyChar();
        if(num == KeyEvent.VK_ENTER)
        jTextLocation.transferFocus();
    }//GEN-LAST:event_jTextLocationKeyTyped

    private void jComboBoxEditionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxEditionKeyTyped
        char num = evt.getKeyChar();
        if(num == KeyEvent.VK_ENTER)
        jButtonAddBook.grabFocus();
    }//GEN-LAST:event_jComboBoxEditionKeyTyped
        String BookNumber = String.valueOf(Number_Of_Books()+1);
        String BookNumberOnline = String.valueOf(Number_Of_Books_Online()+1);
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(Online.equals("YES")){
            jTextBookId.setText(BookNumberOnline);
            jTextBookId.setEditable(false);
        }
        else{
        jTextBookId.setText(BookNumber);
        jTextBookId.setEditable(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextNumbersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumbersKeyTyped
        char num = evt.getKeyChar();
        if(num == KeyEvent.VK_ENTER)
        jTextLocation.grabFocus();
        
    }//GEN-LAST:event_jTextNumbersKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(Online.equals("YES"))    {
                All_Books all = new All_Books();
                all.setVisible(true);
                all.Online = "YES";
                all.setLocationRelativeTo(null);
                all.pack();
                this.dispose();    
        }
        else    {
                All_Books all = new All_Books();
                all.setVisible(true);
                all.setLocationRelativeTo(null);
                all.pack();
                this.dispose();
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
         jButton3.setBackground(new Color(0,102,153));
        jButton3.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
       jButton3.setForeground(Color.BLACK);
        jButton3.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButtonAddBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddBookMouseEntered
        jButtonAddBook.setBackground(new Color(0,102,153));
        jButtonAddBook.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonAddBookMouseEntered

    private void jButtonAddBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddBookMouseExited
         jButtonAddBook.setForeground(Color.BLACK);
        jButtonAddBook.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonAddBookMouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setBackground(new Color(0,102,153));
        jButton5.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setForeground(Color.BLACK);
        jButton5.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        jButton4.setBackground(new Color(0,102,153));
        jButton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jButton4.setForeground(Color.BLACK);
        jButton4.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setBackground(new Color(0,102,153));
        jButton2.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setForeground(Color.BLACK);
        jButton2.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton2MouseExited

    private File showFileDialog(final boolean open) {
    JFileChooser fc = new JFileChooser("Open a File");
    javax.swing.filechooser.FileFilter ff = new javax.swing.filechooser.FileFilter() {
       @Override
       public boolean accept(java.io.File f) {
          String name = f.getName().toLowerCase();
          if(open)
             return f.isDirectory() ||
                name.endsWith(".jpeg") || name.endsWith(".png") || name.endsWith(".jpg");
          return f.isDirectory()||name.endsWith(".txt");
          }
       @Override
       public String getDescription() {
          if(open)
             return "Picture (*.jpeg, *.png)";
          return "Text (*.txt)";
          }
       };
    fc.setAcceptAllFileFilterUsed(false);
    fc.addChoosableFileFilter(ff);

    java.io.File f = null;
   if(open && fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){    
       f = fc.getSelectedFile();
       ImagePath  =  fc.getSelectedFile().getAbsolutePath();
   }
    else if(!open && fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
      f = fc.getSelectedFile();
        
    return f;
    } 
    
/******************** Already Book exist in database.**************************
     * @param Id    
     * @return  *************************/    
    int countof = 0;
     public boolean AlreadyExist(String Id){ 
        boolean alreadyExist = false;
        String query = "SELECT * FROM book where book_id =?";
        try {
            conn con = new conn();
            PreparedStatement st = con.c.prepareStatement(query);
            st.setString(1, Id);
            ResultSet rs = st.executeQuery();
            
            if(rs.next()){
                alreadyExist = true;
                JOptionPane.showMessageDialog(null,"This Id Already Exist");
                int id = Integer.valueOf(jTextBookId.getText());
                id = id+1;
                jTextBookId.setText(String.valueOf(id));
                countof ++;
                if(count > 2) {
                    jTextBookId.setEditable(true);
                    jTextBookId.setText("Choose a unique Id");
                    countof = 0;
                }
            }
                    st.close();
                    con.c.close();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error please Try Again Later!");
        }
        return alreadyExist;
    }
    int count = 0;
    public boolean AlreadyExist_Online(String Id){ 
        boolean alreadyExist = false;
        
        String query = "SELECT * FROM book where book_id =?";
        try {
            conn con = new conn("YES");
            PreparedStatement st = con.c.prepareStatement(query);
            st.setString(1, Id);
            ResultSet rs = st.executeQuery();
            
            if(rs.next()){
                alreadyExist = true;
                JOptionPane.showMessageDialog(null,"This Id Already Exist");
                int id = Integer.valueOf(jTextBookId.getText());
                id = id+1;
                count ++;
                jTextBookId.setText(String.valueOf(id));
                if(count > 2) {
                    jTextBookId.setEditable(true);
                    jTextBookId.setText("Choose a unique Id");
                    count = 0;
                }
            }
                    st.close();
                    con.c.close();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error please Try Again Later!");
        }
        return alreadyExist;
    }
     
     
     private void ResetAll(){
        jLabelPicture.setIcon(null);
        jTextBookId.setText(String.valueOf(Number_Of_Books()+1));
        jTextBookName.setText("");
        jTextBookPublisher.setText("");
        jTextPrice.setText("");
        jTextNumbers.setValue(0);
        jTextLocation.setText("");
        jComboBoxEdition.setSelectedIndex(0);
        jTextBookId.grabFocus();
        this.validate();
     }
     private void ResetAllOnline(){
        jLabelPicture.setIcon(null);
        jTextBookId.setText(String.valueOf(Number_Of_Books_Online()+1));
        jTextBookName.setText("");
        jTextBookPublisher.setText("");
        jTextPrice.setText("");
        jTextBookId.setEditable(false);
        jTextNumbers.setValue(0);
        jTextLocation.setText("");
        jComboBoxEdition.setSelectedIndex(0);
        jTextBookId.grabFocus();
        this.validate();
     }
     
     
     private int Number_Of_Books() {
        String query = "SELECT COUNT(*) FROM book";
        ResultSet rs;
        int numberRow = 0;
        try {
            conn con = new conn();
            PreparedStatement st = con.c.prepareStatement(query);
            rs = st.executeQuery();
            while(rs.next()){
                    numberRow = rs.getInt("count(*)");
                }
                    st.close();
                    con.c.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error");
            }     
            return numberRow;
    }
     
     private int Number_Of_Books_Online() {
        String query = "SELECT COUNT(*) FROM book";
        ResultSet rs;
        int numberRow = 0;
        try {
            conn con = new conn("YES");
            PreparedStatement st = con.c.prepareStatement(query);
            rs = st.executeQuery();
            while(rs.next()){
                    numberRow = rs.getInt("count(*)");
                }
                    st.close();
                    con.c.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error");
            }     
            return numberRow;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Add_Book().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAddBook;
    private javax.swing.JComboBox jComboBoxEdition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextBookId;
    private javax.swing.JTextField jTextBookName;
    private javax.swing.JTextField jTextBookPublisher;
    private javax.swing.JTextField jTextLocation;
    private javax.swing.JSpinner jTextNumbers;
    private javax.swing.JTextField jTextPrice;
    // End of variables declaration//GEN-END:variables
}
