
package Settings;

import Coding.SplashScreen;
import Coding.conn;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hadi
 */
public class Forget_Password extends javax.swing.JFrame {

    public Forget_Password() {
        initComponents();
        jLabelYourPassword.setVisible(false);
        jTextPassword.setVisible(false);
        jTextQuestion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextAnswer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextUserName = new javax.swing.JTextField();
        jTextQuestion = new javax.swing.JTextField();
        jTextPassword = new javax.swing.JTextField();
        jLabelYourPassword = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(16, 18, 24));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAnswer.setBackground(new java.awt.Color(35, 35, 35));
        jTextAnswer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextAnswer.setForeground(new java.awt.Color(254, 254, 254));
        jTextAnswer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextAnswer.setSelectedTextColor(new java.awt.Color(80, 80, 80));
        jTextAnswer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAnswerFocusGained(evt);
            }
        });
        jTextAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAnswerActionPerformed(evt);
            }
        });
        jTextAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAnswerKeyTyped(evt);
            }
        });
        jPanel1.add(jTextAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 235, 39));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Find you password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 12, 300, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 80, 419, 10));

        jTextUserName.setBackground(new java.awt.Color(50, 50, 50));
        jTextUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextUserName.setForeground(new java.awt.Color(193, 193, 193));
        jTextUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextUserName.setText("username");
        jTextUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextUserNameFocusLost(evt);
            }
        });
        jTextUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextUserNameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 236, 40));

        jTextQuestion.setBackground(new java.awt.Color(50, 50, 50));
        jTextQuestion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextQuestion.setForeground(new java.awt.Color(193, 193, 193));
        jTextQuestion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextQuestion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextQuestionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextQuestionFocusLost(evt);
            }
        });
        jTextQuestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextQuestionKeyTyped(evt);
            }
        });
        jPanel1.add(jTextQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 166, 370, 40));

        jTextPassword.setBackground(new java.awt.Color(35, 35, 35));
        jTextPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPassword.setForeground(new java.awt.Color(254, 254, 254));
        jTextPassword.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextPassword.setSelectedTextColor(new java.awt.Color(80, 80, 80));
        jTextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPasswordActionPerformed(evt);
            }
        });
        jTextPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(jTextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 320, 373, 39));

        jLabelYourPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelYourPassword.setForeground(new java.awt.Color(0, 255, 51));
        jLabelYourPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelYourPassword.setText("Your Password");
        jPanel1.add(jLabelYourPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 278, 373, 36));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setOpaque(true);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 180, 50));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setText("Login");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setOpaque(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 180, 50));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 30, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton7.setText("search user");
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setOpaque(true);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 40));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton8.setText("Confirm");
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setOpaque(true);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAnswerActionPerformed

    private void jTextAnswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAnswerKeyTyped
        char num = evt.getKeyChar();
        if(num == KeyEvent.VK_ENTER)
            FindCheckPassword();
    }//GEN-LAST:event_jTextAnswerKeyTyped

    private void jTextUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextUserNameFocusGained

        if(jTextUserName.getText().trim().equals("username")){
            jTextUserName.setText("");
            jTextUserName.setForeground(Color.white);

        }
    }//GEN-LAST:event_jTextUserNameFocusGained

    private void jTextUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextUserNameFocusLost

        if(jTextUserName.getText().trim().equals("")||
            jTextUserName.getText().trim().equals("username")){
            jTextUserName.setText("username");
            jTextUserName.setForeground(new Color(153,153,153,153));
        }
    }//GEN-LAST:event_jTextUserNameFocusLost

    private void jTextUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUserNameKeyTyped
        char num = evt.getKeyChar();
        if(num == KeyEvent.VK_ENTER){
            FindUserName();
        }
    }//GEN-LAST:event_jTextUserNameKeyTyped

    private void jTextQuestionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextQuestionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestionFocusGained

    private void jTextQuestionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextQuestionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestionFocusLost

    private void jTextQuestionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextQuestionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestionKeyTyped

    private void jTextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPasswordActionPerformed

    private void jTextPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPasswordKeyTyped

    private void jTextAnswerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAnswerFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAnswerFocusGained

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        jButton4.setBackground(new Color(0,102,153));
        jButton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jButton4.setForeground(Color.BLACK);
        jButton4.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setBackground(new Color(0,102,153));
        jButton5.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setForeground(Color.BLACK);
        jButton5.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try {
                conn con = new conn();
                String sql ="SELECT * FROM account where username=? AND password=?" ;
                PreparedStatement st = con.c.prepareStatement(sql);
                st.setString(1, jTextUserName.getText());
                st.setString(2, String.valueOf(jTextPassword.getText()));
                ResultSet rs = st.executeQuery();
                rs.next();
                
                if(rs.getRow() == 1){
                    SplashScreen sp = new SplashScreen();
                    sp.setVisible(true);
                    sp.pack();
                    sp.setLocationRelativeTo(null);
                    this.dispose();                    
                    st.close();
                    con.c.close();
                    }
                }
                catch(Exception e){
                        
                        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        jButton7.setBackground(new Color(0,102,153));
        jButton7.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        jButton7.setForeground(Color.BLACK);
        jButton7.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        FindUserName();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        jButton8.setBackground(new Color(0,102,153));
        jButton8.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        jButton8.setForeground(Color.BLACK);
        jButton8.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        FindCheckPassword();
    }//GEN-LAST:event_jButton8ActionPerformed

   
    private boolean FindUserName(){
        String sql = "select * from account where username=?";
        try{
                conn con = new conn();
		PreparedStatement st = con.c.prepareStatement(sql);

		st.setString(1, jTextUserName.getText());
		ResultSet rs = st.executeQuery();

		if (rs.next()) {
                    jTextQuestion.setText(rs.getString("sec_question"));
                    jTextQuestion.setEnabled(true);
                    jTextQuestion.setEditable(false);
                    jTextAnswer.grabFocus();
                    st.close();
                    con.c.close();
		}
                else{
                    JOptionPane.showMessageDialog(this, "کاربر موجود نیست");
                    st.close();
                    con.c.close();
                }
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(this, "خطای سرور");
        }
        return true;
    }
    
    
    
    private void FindCheckPassword(){
        try{
                conn con = new conn();
                String sql = "select * from account where username=? AND sec_answer=?";
		PreparedStatement st = con.c.prepareStatement(sql);

                st.setString(1, jTextUserName.getText());
		st.setString(2, jTextAnswer.getText());
		ResultSet rs = st.executeQuery();
                rs.next();
		if (rs.getRow() == 1) {
                    	jTextPassword.setText(rs.getString("password"));
                        jLabelYourPassword.setVisible(true);
                        jTextPassword.setVisible(true);
                        st.close();
                        con.c.close();
		}
                else{
                    JOptionPane.showMessageDialog(this, "جواب شما اشتباه است");
                    jLabelYourPassword.setVisible(false);
                    jTextPassword.setVisible(false);
                    st.close();
                    con.c.close();
                }
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(this, "خطای سرور");
        }
    }
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Forget_Password().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelYourPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextAnswer;
    private javax.swing.JTextField jTextPassword;
    private javax.swing.JTextField jTextQuestion;
    private javax.swing.JTextField jTextUserName;
    // End of variables declaration//GEN-END:variables
}
