package Tables;

import Coding.conn;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Hadi
 */
public class Sold_Books_Table extends javax.swing.JFrame {

    private TableRowSorter sorter;
    Font headerFont = new Font("Arial", Font.BOLD, 17);
    JTableHeader tableHeader;
    DefaultTableCellRenderer renderer;
    
    File file = new File("Icon.png");
    String absolutePath = file.getAbsolutePath().replace("Icon.png", "/src/Images/Icon.png");
    ImageIcon FrameIcon = new ImageIcon(absolutePath);
       
    public String Online = "NO";
    
    public Sold_Books_Table() {
        initComponents();
    this.setIconImage(FrameIcon.getImage());
        this.tableHeader = jTableSoldBooks.getTableHeader();
        tableHeader.setFont(headerFont);
        
        this.renderer = (DefaultTableCellRenderer)
        jTableSoldBooks.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSoldBooks = new javax.swing.JTable();
        jButtonDelete = new javax.swing.JButton();
        jButtonSearch2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LIST OF SOLD BOOKS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextFieldSearch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextFieldSearch.setForeground(new java.awt.Color(133, 133, 133));
        jTextFieldSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldSearch.setText("Search");
        jTextFieldSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchFocusLost(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyTyped(evt);
            }
        });

        jButtonSearch.setBackground(new java.awt.Color(0, 51, 51));
        jButtonSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch.setText("Search");
        jButtonSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jTableSoldBooks.setAutoCreateRowSorter(true);
        jTableSoldBooks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTableSoldBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sale Id", "Book Id", "BookName", "Publisher", "Price", "Availability", "Discount", "Total", "Date of Sale"
            }
        ));
        jTableSoldBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableSoldBooks.setFocusable(false);
        jTableSoldBooks.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableSoldBooks.setName(""); // NOI18N
        jTableSoldBooks.setRowHeight(30);
        jTableSoldBooks.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTableSoldBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSoldBooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSoldBooks);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButtonDelete.setBackground(new java.awt.Color(0, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Remove");
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSearch2.setBackground(new java.awt.Color(0, 51, 51));
        jButtonSearch2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSearch2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch2.setText("Excel");
        jButtonSearch2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearch2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSearch)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButtonSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchFocusGained
        if(jTextFieldSearch.getText().trim().equals("Search")){
            jTextFieldSearch.setText("");
            jTextFieldSearch.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldSearchFocusGained

    private void jTextFieldSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchFocusLost
        if(jTextFieldSearch.getText().trim().equals("")||
            jTextFieldSearch.getText().trim().equals("Search")){
            jTextFieldSearch.setText("Search");
            jTextFieldSearch.setForeground(new Color(133,133,133));
        }
    }//GEN-LAST:event_jTextFieldSearchFocusLost

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jTextFieldSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyTyped
   
    }//GEN-LAST:event_jTextFieldSearchKeyTyped

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        searchTable();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTableSoldBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSoldBooksMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableSoldBooksMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(Online.equals("YES"))
            LoadAllSoldBooks_Online();    
        else
            LoadAllSoldBooks();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if(Online.equals("YES"))
            DeleteBook_Online();
        else
            DeleteBook();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearch2ActionPerformed
        SaveToExcel();
    }//GEN-LAST:event_jButtonSearch2ActionPerformed

    private void LoadAllSoldBooks(){ 
        try {
            ResultSet rs;
            conn con = new conn();
            String sql ="SELECT * FROM soldbooks";
            DefaultTableModel modele = (DefaultTableModel) jTableSoldBooks.getModel();        
            PreparedStatement st = con.c.prepareStatement(sql);
            rs = st.executeQuery();
            while(rs.next()){
            Object o[]= {rs.getString("sale_id"), rs.getString("bookId"), rs.getString("bookName"), rs.getString("publisher")
                    ,rs.getString("price"), rs.getString("Numbers"), rs.getString("discount")
                    ,rs.getString("total") ,rs.getString("date")};
            if(jTableSoldBooks.getRowCount()!= Number_Of_Sold_Books())    
                modele.addRow(o);                
            }
                st.close();
                con.c.close();
        } catch(SQLException ex) {
              JOptionPane.showMessageDialog(this, "Error");
            }
    }  
    private void LoadAllSoldBooks_Online(){ 
        try {
            ResultSet rs;
            conn con = new conn("YES");
            String sql ="SELECT * FROM soldbooks";
            DefaultTableModel modele = (DefaultTableModel) jTableSoldBooks.getModel();        
            PreparedStatement st = con.c.prepareStatement(sql);
            rs = st.executeQuery();
            while(rs.next()){
            Object o[]= {rs.getString("sale_id"), rs.getString("bookId"), rs.getString("bookName"), rs.getString("publisher")
                    ,rs.getString("price"), rs.getString("Numbers"), rs.getString("discount")
                    ,rs.getString("total") ,rs.getString("date")};
            if(jTableSoldBooks.getRowCount()!= Number_Of_Sold_Books_Online())    
                modele.addRow(o);                
            }
                st.close();
                con.c.close();
        } catch(SQLException ex) {
              JOptionPane.showMessageDialog(this, "Error");
            }
    }
    private int Number_Of_Sold_Books_Online() {
        String query = "SELECT COUNT(*) FROM soldbooks";
        ResultSet rs;
        int numberRow = 0;
        try {
            conn con = new conn("YES");
            PreparedStatement st = con.c.prepareStatement(query);
            rs = st.executeQuery();
            while(rs.next()){
                    numberRow = rs.getInt("count(*)");
                }
                st.close();
                con.c.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error");
            }     
            return numberRow;
    }
    private int Number_Of_Sold_Books() {
        String query = "SELECT COUNT(*) FROM soldbooks";
        ResultSet rs;
        int numberRow = 0;
        try {
            conn con = new conn();
            PreparedStatement st = con.c.prepareStatement(query);
            rs = st.executeQuery();
            while(rs.next()){
                    numberRow = rs.getInt("count(*)");
                }
                st.close();
                con.c.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error");
            }     
            return numberRow;
    }
    private void searchTable()  {
      DefaultTableModel model = (DefaultTableModel) jTableSoldBooks.getModel();
            sorter = new TableRowSorter<>(model);
            jTableSoldBooks.setRowSorter(sorter);
                String str = jTextFieldSearch.getText();
                    if  (str.length() == 0) 
                        sorter.setRowFilter(null);
                    else 
                        sorter.setRowFilter(RowFilter.regexFilter(str));
    }
    private void DeleteBook()  {
        DefaultTableModel model = 
            (DefaultTableModel) jTableSoldBooks.getModel();
        if(jTableSoldBooks.getSelectedRow() == -1){
            if(jTableSoldBooks.getRowCount()==0) {
                JOptionPane.showMessageDialog(null, "No Row has been Selected",
                    "Alert!", JOptionPane.OK_OPTION);
            } else
            JOptionPane.showMessageDialog(null, "Select a Row to be Deleted",
                "Student Records System", JOptionPane.OK_OPTION);
        }
        else{
     
            Object[] options = {"Yes", "No"};
            int confirm = JOptionPane.showOptionDialog(this,
            "Are You Sure ?",
            "Warning",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,     //do not use a custom Icon
            options,  //the titles of buttons
            options[0]); //default button title
                if (confirm == JOptionPane.YES_OPTION) {
                     String Sale_Id = jTableSoldBooks.getValueAt(jTableSoldBooks.getSelectedRow(), 0).toString();
                     String Book_Id = jTableSoldBooks.getValueAt(jTableSoldBooks.getSelectedRow(), 1).toString();

                    String sql = "DELETE FROM soldbooks"
                                +" WHERE( sale_Id = "+'"'+Sale_Id+'"'+" AND"
                                +" bookId="+'"'+Book_Id+'"'+" )";
                    try {
                        conn con = new conn();
                        PreparedStatement st = con.c.prepareStatement(sql);
                        st.executeUpdate();
                        st.close();
                        con.c.close();
                    } catch(Exception e) {
                        JOptionPane.showMessageDialog(null,"Can Not Delete At this Moment! Try Later"+e.getMessage());
                    }
                    model.removeRow(jTableSoldBooks.getSelectedRow());
                    }
            }                
    }
    private void DeleteBook_Online()  {
        DefaultTableModel model = 
            (DefaultTableModel) jTableSoldBooks.getModel();
        if(jTableSoldBooks.getSelectedRow() == -1){
            if(jTableSoldBooks.getRowCount()==0) {
                JOptionPane.showMessageDialog(null, "No Row has been Selected",
                    "Alert!", JOptionPane.OK_OPTION);
            } else
            JOptionPane.showMessageDialog(null, "Select a Row to be Deleted",
                "Student Records System", JOptionPane.OK_OPTION);
        }
        else{
     
            Object[] options = {"Yes", "No"};
            int confirm = JOptionPane.showOptionDialog(this,
            "Are You Sure ?",
            "Warning",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,     //do not use a custom Icon
            options,  //the titles of buttons
            options[0]); //default button title
                if (confirm == JOptionPane.YES_OPTION) {
                     String Sale_Id = jTableSoldBooks.getValueAt(jTableSoldBooks.getSelectedRow(), 0).toString();
                     String Book_Id = jTableSoldBooks.getValueAt(jTableSoldBooks.getSelectedRow(), 1).toString();

                    String sql = "DELETE FROM soldbooks"
                                +" WHERE( sale_Id = "+'"'+Sale_Id+'"'+" AND"
                                +" bookId="+'"'+Book_Id+'"'+" )";
                    try {
                        conn con = new conn("YES");
                        PreparedStatement st = con.c.prepareStatement(sql);
                        st.executeUpdate();
                        st.close();
                        con.c.close();
                    } catch(Exception e) {
                        JOptionPane.showMessageDialog(null,"Can Not Delete At this Moment! Try Later"+e.getMessage());
                    }
                    model.removeRow(jTableSoldBooks.getSelectedRow());
                    }
            }                
    }
    
        private void SaveToExcel(){
        try{
           JFileChooser jFileChooser = new JFileChooser();
           jFileChooser.showSaveDialog(this);
           File saveFile = jFileChooser.getSelectedFile();
           
           if(saveFile != null){
               saveFile = new File(saveFile.toString()+".xlsx");
               Workbook wb = new XSSFWorkbook();
               Sheet sheet = wb.createSheet("customer");
               
               Row rowCol = sheet.createRow(0);
               for(int i=0;i<jTableSoldBooks.getColumnCount();i++){
                   Cell cell = rowCol.createCell(i);
                   cell.setCellValue(jTableSoldBooks.getColumnName(i));
               }
               
               for(int j=0;j<jTableSoldBooks.getRowCount();j++){
                   Row row = sheet.createRow(j+1);
                   for(int k=0;k<jTableSoldBooks.getColumnCount();k++){
                       Cell cell = row.createCell(k);
                       if(jTableSoldBooks.getValueAt(j, k)!=null){
                           cell.setCellValue(jTableSoldBooks.getValueAt(j, k).toString());
                       }
                   }
               }
               FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
               wb.write(out);
               wb.close();
               out.close();
               JOptionPane.showMessageDialog(null, "File Has Been Saved");
           }else{
               JOptionPane.showMessageDialog(null,"Error Please Try Again Later");
           }
       }catch(FileNotFoundException e){
           System.out.println(e);
       }catch(IOException io){
           System.out.println(io);
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sold_Books_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sold_Books_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sold_Books_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sold_Books_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Sold_Books_Table().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSearch2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSoldBooks;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
